services:
  - type: web
    name: productdesk
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: productdesk-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://productdesk.org
      - key: APP_URL
        value: https://productdesk.org
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: "ProductDesk <onboarding@resend.dev>"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

databases:
  - name: productdesk-db
    plan: free
