import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        // Material-3-style semantic tokens from the "Stitch Inventory Hub Premium" design system.
        'surface-variant': '#e1e3e4',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d9dadb',
        'error-container': '#ffdad6',
        'secondary-fixed': '#dce2f7',
        'surface-container-low': '#f3f4f5',
        'surface-tint': '#494bd6',
        'on-error': '#ffffff',
        'inverse-primary': '#c0c1ff',
        'on-tertiary-fixed-variant': '#005236',
        error: '#ba1a1a',
        'surface-container-highest': '#e1e3e4',
        'on-secondary-container': '#5c6274',
        'on-primary-container': '#fffbff',
        'tertiary-container': '#00885d',
        'tertiary-fixed-dim': '#4edea3',
        outline: '#767586',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#000703',
        background: '#f8f9fa',
        'surface-container': '#edeeef',
        'on-error-container': '#93000a',
        'on-surface': '#191c1d',
        'on-tertiary-fixed': '#002113',
        'primary-fixed-dim': '#c0c1ff',
        'on-secondary-fixed-variant': '#404758',
        surface: '#f8f9fa',
        'on-primary-fixed': '#07006c',
        'tertiary-fixed': '#6ffbbe',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-secondary': '#ffffff',
        'primary-fixed': '#e1e0ff',
        'surface-bright': '#f8f9fa',
        'on-secondary-fixed': '#141b2b',
        'inverse-surface': '#2e3132',
        'secondary-fixed-dim': '#c0c6db',
        'surface-container-high': '#e7e8e9',
        primary: '#4648d4',
        'primary-container': '#6063ee',
        tertiary: '#006c49',
        'inverse-on-surface': '#f0f1f2',
        'outline-variant': '#c7c4d7',
        'on-background': '#191c1d',
        'on-surface-variant': '#464554',
        'secondary-container': '#d9dff5',
        secondary: '#575e70',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'container-max-width': '1440px',
        unit: '4px',
        'stack-md': '16px',
        'margin-desktop': '40px',
        'stack-lg': '32px',
        'stack-sm': '8px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max-width': '1440px',
      },
      fontFamily: {
        display: ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-md': ['var(--font-geist-sans)', 'Geist', 'sans-serif'],
        code: ['var(--font-jetbrains-mono)', 'JetBrains Mono', 'monospace'],
        'body-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        code: ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
      boxShadow: {
        card: '0 10px 15px -3px rgba(0,0,0,0.05), 0 4px 6px -2px rgba(0,0,0,0.02)',
      },
    },
  },
  plugins: [],
};

export default config;
